### ISSUE TITLE
Causes Vapor to crash.

### ISSUE THREAD

**Issue by matthewlilley** [scholtzm/vapor-storehouse#1]
I've tested with both the vapor master and develop branches, the same with the plugin branches.
Other plugins are loading fine.

**Comment by scholtzm** [comment]
Can you provide your log?

**Comment by matthewlilley** [comment]
I checked the log, but it's not showing anything. It's easy to reproduce, just download the repo, require the plugin, add your config options and start. 

As soon as it goes to load this plugin it just resets back to the command prompt.

**Comment by scholtzm** [comment]
Hmm that is weird, have you checked the `logs` folder?

**Update:** I'm unable to replicate this problem.

It could be also useful, if you could provide your config, without username and password of course.

**Comment by matthewlilley** [comment]
Yes I checked the logs but there was nothing. It just stops. Here is my config.
{
  "username": "",
  "password": "",
  "displayName": "BOT",
  "admins": [""],
  "logs": {
    "dateFormat": "YYYY-MM-DD HH:mm:ss",
    "consoleLevel": "info",
    "fileLevel": "debug"
  },
  "plugins": {
      "decline-friend-requests": {},
      "vapor-storehouse": {}
  }
}

**Comment by matthewlilley** [comment]
Okay. I've narrowed down the issue. It's only happening on my VM, it works perfectly on my local machine. It could just be that my node is slightly outdated on the VM.

**Comment by scholtzm** [comment]
That's some good news.
Make sure you are running v0.12, ideally v0.12.6 or higher.

Also, I'm perplexed as to why there is no error output either in the console or the log file.

**Comment by matthewlilley** [comment]
i have 0.12.4 on my VM. It's odd because it's only happening with this storehouse plugin and none of the others.

**Comment by scholtzm** [comment]
What about this one? https://github.com/scholtzm/vapor-friendslist

**Comment by matthewlilley** [comment]
Yes, that one works correctly as well. I updated node version 12.6 but I still have the same issue.

**Comment by scholtzm** [comment]
I just installed vapor+storehouse from scratch and it's loading just fine. storehouse is also the only plugin (so far) with external dependency but I'm not sure if that is the problem here.

**Comment by matthewlilley** [comment]
I did add you on Steam, my user is D3. Yeah, it seems to only happen when running on my vagrant box. I've reinstalled multiple times but continue to get the same results.

Here is the vagrant box I am using. http://laravel.com/docs/master/homestead

**Comment by scholtzm** [comment]
Yep, I accepted your friend request and messaged you but you never replied back.

Regarding the vagrant box you are using, I don't know what the issue could be. We can discuss this later once I'm back online on Steam.

**Comment by scholtzm** [comment]
After looking into this further with @MatthewLilley, this seems to be a problem with the Vagrant box so I'm closing this issue for the time being.
